config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :dishes
  resources :categories
  resources :menus

  get 'index', to: 'home#index'
  get 'login', to: 'home#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :category
  has_many :dish_menus
  has_many :menus, through: :dish_menus

  accepts_nested_attributes_for :dish_menus
end

app/models/dish_menu.rb
class DishMenu < ApplicationRecord
  belongs_to :dish
  belongs_to :menu

  accepts_nested_attributes_for :dish
  validates_uniqueness_of :dish_id, scope: %i[menu_id]

end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :dish_menus
  has_many :dishes, through: :dish_menus


  validates_presence_of :dish_menus, message: 'Can not be blank!'
  validates_uniqueness_of :date, message: 'Same Date!'


  accepts_nested_attributes_for :dish_menus,
                                allow_destroy: true,
                                reject_if: proc { |attributes| attributes['included'] == '0' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    redirect_to dishes_path, notice: 'Category was successfully created.' if @category.save
  end

  def update
    @category.update(category_params)
    redirect_to categories_path(@category), notice: 'Category was updated'
  end

  def destroy
    if Dish.find_by(category_id: @category[:id])
      redirect_to categories_path, notice: 'Err! Category has dishes'
    else
      @category.destroy
      redirect_to categories_path, notice: 'Category  destroyed'
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:category)
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[update show destroy edit]

  def create
    @dish = Dish.create(dish_params)
    redirect_to dishes_path, notice: 'dish was created' if @dish.save
  end

  def update
    @dish.update(dish_params)
    redirect_to dish_path(@dish), notice: 'dish was updated'
  end

  def destroy
    @menus = Menu.all

    if @menus.map { |m| m.dishes.include? @dish[:id].to_s }.first == true
      redirect_to dishes_path, notice: 'Error! Dish is included in menu'
    else
      @dish.destroy
      redirect_to dishes_path, notice: 'Dish was destroyed'
    end
  end

  def show
    @category = Category.find(Dish.find(params[:id]).category_id)
  end

  def index
    @menus = Menu.all
    @categories = Category.all
    @dishes = Dish.all
  end

  def new
    @dish = Dish.new
  end

  def edit; end

  private

  def dish_params
    params.require(:dish).permit(:name, :price_type, :price, :category_id)
  end

  def set_dish
    @dish = Dish.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @menus = Menu.all
    @dishes = Dish.all
    @categories = Category.all
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[show edit update destroy]
  before_action :set_dishes, only: %i[edit new index destroy]

  def new
    @menu = Menu.new
    @dishes.count.times { @menu.dish_menus.build }
  end

  def index
    @menus = Menu.all
    @categories = Category.all
  end

  def edit
    redirect_to new_menu_path, alert: 'Must be unique' unless @menu.save

  end

  def destroy
    @menu.destroy
    redirect_to root_path, notice: 'menu was deleted'
  end

  def update
    @menu.update(menu_params)
    redirect_to root_path, notice: 'menu was updated' if @menu.save
  end

  def create
    # binding.pry
    @menu = Menu.create(menu_params)
    redirect_to new_menu_path, alert: 'Must be unique' unless @menu.save
    redirect_to root_path, notice: 'Menu was created' if @menu.save
  end

  def show; end

  private

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def set_dishes
    @dishes = Dish.all
  end

  def menu_params
    params.require(:menu).permit(:date, :id, dish_menus_attributes: %i[dish_id price menu_id included id _destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
  def dish_price_type(dish_id)
    type = @dishes.find(dish_id).price_type
    type.include?('By Weight') ? type.to_i : 1
  end

  def dish_included_in_menu?(menu_id, dish_id)
    el = DishMenu.where(menu_id: menu_id, dish_id: dish_id).first
    el.nil? ? false : el.included
  end

  def dish_price_in_menu(menu_id, dish_id)
    el = DishMenu.where(menu_id: menu_id, dish_id: dish_id)
    el.first.nil? ? Dish.find(dish_id).price : el.min_by { |dish_menu| dish_menu[:date] }.price
  end

  def find_last_dish_price(dish_id)
    dish_in_menu = DishMenu.where(dish_id: dish_id)

    dish_in_menu.exists? ? dish_in_menu.to_a { |e| e[:date] }.last[:price] : Dish.find(dish_id).price
  end
end

app/views/categories/_categories.html.erb
<% @categories.each do |category| %>
  <div type="button" class="card p-2 mx-2 text-center" style="min-width: 6em">
    <%= link_to category[:name],
        category_path(category[:id]),
        class: "text-primary card-title h5 mb-0 text-decoration-none"
    %>
    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary">
      <%= category.dishes.count %>
    </span>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <div class="mt-3">
    <%= f.submit 'Save!', class:'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="text-center pt-5">
  <h1 class="my-3">Edit </h1>
  <%= render "form", category: @category %>
</div>

app/views/categories/index.html.erb
<div id="categories " class="card">
  <div class="card-header d-flex justify-content-center">
    <h2> Categories </h2>
    <%= link_to "➕", new_category_path, class: 'text-decoration-none' %>
  </div>
  <div class="card-body d-flex justify-content-center">
    <% @categories.each do |category| %>
      <div class=" d-flex justify-content-between card w-25 p-1 m-1">
         <div class="fw-bold text-center mt-2">
            <%= category.name %>
         </div>
        <hr class="mx-5">
        <div class="d-flex justify-content-center">
          <%= button_to category, method: :delete, class:"btn px-3" do %>
            <i class="fa-solid fa-trash"></i>
          <%end %>
          <%= link_to  edit_category_path(category[:id]) , class:"btn px-3" do %>
            <i class="fa-solid fa-gear"></i>
          <%end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="text-center pt-5">
  <h1 class="my-3">New Category</h1>
  <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<div class="d-flex justify-content-center mt-5">
  <div class="card p-2 mx-2 text-center" style="width: 40em">
    <h3 class="text-center"><%= @category.name %></h3>
    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary">
      <%= @category.dishes.count %>
    </span>
    <%= @category.dishes.map{  |d| d.name  }%>
    <hr class="mx-5">
    <div class="d-flex justify-content-center">
      <%= button_to @category, method: :delete, class:"btn px-3" do %>
        <i class="fa-solid fa-trash"></i>
      <%end %>
      <%= link_to  edit_category_path(@category[:id]) , class:"btn px-2" do %>
        <i class="fa-solid fa-gear"></i>
      <%end %>
    </div>
  </div>
</div>

app/views/dishes/_dishes.html.erb
<% @dishes.each do |dish|%>
  <div class=' card justify-content-center p-2' style="min-width: 25%">
    <div class="mx-2 text-center">
      <%=
        link_to dish.name,
        dish_path(dish.id),
        class: 'text-primary fw-bold card-title h5 mb-0 text-decoration-none '
      %>
    </div>
  </div>
<% end %>

app/views/dishes/_form.html.erb
<% price_types = [' 25 | By Weight', ' 50 | By Weight', ' 100 | By Weight', 'By Item'] %>

<div class="d-flex justify-content-center my-5">
  <%= form_for @dish do |f| %>
    <div class="my-2 d-flex">
      <%= f.label :name %>
      <span class="px-3"><%= f.text_field :name , class: 'form-control' %></span>
    </div>

    <div class="my-2 d-flex">
      <%= f.label :category_id %>
      <span class="px-3">
        <%= f.select :category_id, Category.all.map{|c| [c.name,c.id]}, class: 'form-control'%>
      </span>
    </div>
    <div class="my-2 d-flex">
      <%= f.label :price_type %>
      <span class="px-2"> <%= f.select :price_type, price_types, class: 'form-control' %></span>
    </div>
    <div class="mt-2 d-flex">
      <%= f.label :price %>
      <span class="px-4"><%= f.text_field :price , class: 'form-control' %></span>
    </div>
    <div class='my-3 text-center'><%= f.submit 'Save', class: 'btn btn-outline-secondary' %></div>
  <% end %>
</div>

app/views/dishes/edit.html.erb
<h2 class='text-center'>Edit <%= @dish.name %></h2>
<%= render 'form' %>

app/views/dishes/index.html.erb
<div class="row">
  <div class='col'>
    <div class="card">
      <div class="card-header d-flex justify-content-center">
        <h2> Dishes </h2>
        <%= link_to  new_dish_path do %>
          <i class="fa fa-plus fs-4"></i>
        <%end %>
      </div>
      <div class="d-flex gap-3 m-3 justify-content-center">
         <%= render 'dishes' %>
      </div>
    </div>
  </div>
</div>

app/views/dishes/new.html.erb
<h2 class='text-center '> Create New Dish</h2>
<%= render 'form' %>

app/views/dishes/show.html.erb
<h2 class='text-center my-5'> <%=@dish.name.capitalize %> Details</h2>
<div class="d-flex justify-content-center">
  <div class='p-3 card w-25 p-5'>
    <span>
      <b>Name:</b>
      <%=@dish.name.capitalize %>
    </span>
    <span>
      <b>Price: </b>
      <%= @dish.price%>
    </span>
    <span>
      <b>Category: </b>
      <%= @category.name%>
    </span>
    <span>
     <b>Price type: </b>
      <%= @dish.price_type %>
    </span>
    <hr class="mx-1">
    <div class='mt-1 btn-group d-flex justify-content-center'>
      <%= button_to dish_path, method: :delete, class:"btn px-4" do %>
        <i class="fa-solid fa-trash"></i>
      <%end %>
      <div>
        <%= link_to  edit_dish_path , class:"btn px-4" do %>
          <i class="fa-solid fa-gear"></i>
        <%end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <%= @f %>
  <header class="mb-4">
    <h1 class='text-center mb-0'>
      <%= Date.today.strftime("%e %b %Y") %>
    </h1>
    <div class="text-center">
      <%= link_to   '👉 Create Today Menu 👈', new_menu_path, class: 'text-decoration-none fw-bold text-secondary' %>
    </div>
  </header>
  <div class='col-8 '>
    <div class="card">
      <div class="card-header d-flex justify-content-center">
        <h2> Dishes </h2>
        <%= link_to  new_dish_path do %>
          <i class="fa fa-plus fs-4"></i>
        <%end %>
      </div>
      <div class="d-flex gap-3 m-3 ">
        <%= render 'dishes/dishes' %>
      </div>
    </div>
  </div>

  <div class='col-4'>
    <div class="card">
      <div class="card-header d-flex justify-content-center">
        <h2 class='text-decoration-none'>Categories</h2>
        <%= link_to  new_category_path do %>
          <i class="fa fa-plus fs-4"></i>
        <%end %>
      </div>
      <div class="d-flex gap-3 m-3 flex-wrap">
        <%= render 'categories/categories' %>
      </div>
    </div>
  </div>

  <div class="col mt-3">
    <div class="card">
      <div class="card-header d-flex justify-content-center">
        <h2 class="text-decoration-none ">Menus</h2>
        <%= link_to  new_menu_path do %>
          <i class="fa fa-plus fs-4"></i>
        <%end %>
      </div>
      <div class="card-body mt-1 d-flex flex-wrap justify-content-center">
        <%= render 'menus/menu' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMenu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container" id="navbarNavAltMarkup">
      <div class="navbar-nav justify-content-between d-inline-flex w-100">
        <% if user_signed_in? %>
         <span class="d-inline-flex mx-2">
           <%= link_to 'Home',root_path, class: "nav-item nav-link" %>
           <%= link_to 'Dishes',dishes_path, class: "nav-item nav-link mx-2" %>
           <%= link_to 'Categories',categories_path, class: "nav-item nav-link" %>
           <%= link_to 'Menus',menus_path, class: "nav-item nav-link mx-2" %>
         </span>
         <span class="d-inline-flex mx-2 justify-self-end" >
           <%= link_to current_user.email, edit_user_registration_path, class: 'text-muted py-2 mx-2
           text-decoration-none' %>
           <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary mx-2 py-2' %>
         </span>
        <%  else %>
          <div>
            <%= link_to 'Log In ', new_user_session_path, class: 'btn btn-outline-secondary  py-2'  %>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-secondary py-2'  %>
          </div>
        <% end %>

      </div>
    </div>
  </nav>
  <div class='container mt-4'>
    <% if flash[:notice].present? %>
      <p class='text-center alert alert-warning alert-dismissible fade show'>
        <%= flash[:notice]%>
      </p>
    <% end %>

    <% if flash[:alert].present?  %>
      <p class="alert alert-danger"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/menus/_dish_menu_row.html.erb
<div class="nested-fields">
  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>


</div>

app/views/menus/_dishes_in_menu.html.erb
<%= menu_form.fields_for :dish_menus do |dish_menus_form| %>
  <% @dishes.each do |dish| %>
    <div class="d-flex justify-content-between align-items-center my-1">
      <div class="mb-1 mx-2"><%= dish_menus_form.check_box :included %></div>
      <h5>  <%= dish.name %></h5>
      <div class="d-flex justify-content-end align-items-center ">
        <%= dish_menus_form.label :price, '$' %>
        <span class="mx-2">  <%= dish.price_type %></span>
        <%= dish_menus_form.text_field :price , value:dish.price, class:"form-control w-25 " %>
        <%= dish_menus_form.hidden_field :dish_id, value:dish.id%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/menus/_form.html.erb
<div class="card p-3 m-auto mt-5" style="width: 450px;">

  <%= nested_form_for @menu do |menu_form| %>
    <div class="my-3 ">
      <h2>
        <%= menu_form.label :date %>
      </h2>
      <div>
        <%= menu_form.date_select :date %>
      </div>
    </div>
    <%= menu_form.fields_for :dish_menus do |dish_menus_form| %>
      <% random_dish_id = Dish.all.map(&:id).sample %>
      <div class="d-flex align-items-center my-1 justify-content-between">
        <div class="d-flex">
          <span>✔️</span>
          <span class="mx-1"><%= dish_menus_form.check_box :included %></span>
        </div>
        <div class="mx-2">
          <%=  dish_menus_form.select :dish_id,
                                      @dishes.map{ |dish| [dish.name, dish.id] },
                                      class: 'form-control',
                                      :selected => @dishes[dish_menus_form.index.to_i].id
                                      # :selected => Dish.find(random_dish_id).id
          %>
        </div>
        <div class="justify-items-end">
          <%= dish_menus_form.text_field :price,
                                         placeholder: "Price",
                                         # value: find_last_dish_price(random_dish_id),
                                         value: find_last_dish_price(@dishes[dish_menus_form.index.to_i].id),
                                         class: 'form-control py-0'
          %>
        </div>

       <div>
         <%= dish_menus_form.link_to_remove "", class: 'btn btn-outline-secondary fa-solid fa-trash my-1' %>
       </div>
      </div>
    <% end %>
    <p><%= menu_form.link_to_add "", :dish_menus, class: 'btn btn-outline-secondary fa-solid fa-plus mx-1'%></p>
    <div class='my-3 text-center'><%= menu_form.submit 'Save', class: 'btn btn-outline-secondary' %></div>
  <%end %>
</div>

<script>
  document.querySelectorAll("select").forEach( s => s.addEventListener('change',(e)=> {
      const selectName = e.target.name.slice(0, -9);
      const selectId =
          <%= javascript_tag do %>
          window.productsURL = '<%= j products_url %>';
      <% end %>
          <% @a =  %>e.target.value
          `<% find_last_dish_price(${selectId}) %>`
      document.getElementsByName(`${selectName}[price]`)[0].value
  }))
</script>

app/views/menus/_menu.html.erb
<% @menus.each do |m| %>
  <div class="card px-0  m-1" style="width: 32%;" >
    <div class="card-header d-flex px-3 justify-content-between align-center" style="background-color: #8EB3CD;">
      <h5 class=" d-flex card-title m-2 "><%= m.date %></h5>
      <span class="d-flex">
        <%= button_to m, method: :delete, class:"btn px-2" do %>
          <i class="fa-solid fa-trash"></i>
        <%end %>
        <%= link_to  edit_menu_path(m[:id]), class:"btn px-2" do %>
          <i class="fa-solid fa-gear"></i>
        <%end %>
      </span>
    </div>
    <div class="card-body justify-content-between mx-2">
        <% total = 0 %>
        <%  m.dish_menus.each_with_index  do |dish, index|%>
          <% total += dish.price %>
            <div class="d-flex justify-content-between">
             <div>
               <%= index + 1 %>
               "<%= @dishes.find(dish.dish_id).name %>"
             </div>
             <div>
               <%= dish_price_type(dish.dish_id) %>
                /
               <%=  dish.price  %> $
             </div>
            </div>
        <% end %>
    </div>
    <div class="card-footer text-muted d-flex justify-content-end">
       <span class="m-2"> <b>Total:</b> <%= total %> $ </span>
    </div>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1> Editing Menu # <%= @menu.id %> </h1>
<%= render 'form' %>

app/views/menus/index.html.erb
<h1 class="text-center">Menus</h1>
<div class="row mt-4 m-0  d-flex flex-row">
 <%= render 'menu' %>
</div>

app/views/menus/new.html.erb
<h1 class="text-center"> New Menu</h1>
<%= render 'form' %>

app/views/menus/show.html.erb
<%= button_to "Destroy", menu_path, method: :delete %>